---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: happy-svc
  name: happy-svc
  namespace: default
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    run: happy-svc
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: happy-svc
  name: happy-svc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: happy-svc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: happy-svc
    spec:
      containers:
      - image: samsulmaarif/k8s-samsul:happy
        imagePullPolicy: Always
        name: happy-svc
        env:
          - name: LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                name: happy-config
                key: log_level
        ports:
        - containerPort: 4000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/happy/healthz
            port: 4000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/happy/healthz
            port: 4000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1    
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
