kind: PersistentVolume
apiVersion: v1
metadata:
  name: calculator-volume
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /k8s/nfs-share/redis-calculator
    server: 10.10.1.13
